import fs from "node:fs";
import path from "node:path";
export type MarketplaceKind="skill"|"tool"|"operator";
export type AdapterPlatform="openai"|"claude"|"codex"|"mcp"|"api"|"vscode"|"saas";
export type MarketplaceListing={id:string;slug:string;name:string;kind:MarketplaceKind;theme:string;status:string;availability:string;tagline:string;description:string;version:string;publisher:string;capabilities:string[];platforms:AdapterPlatform[];components?:string[];source:Record<string,unknown>;packagePath?:string;instructionStatus?:"canonical"|"composed"|"source-unavailable";publisherMeta?:{name:string;type:string};trust?:{verified:boolean;status:string};license?:string;pricing?:{model:string;free:boolean;commercialUse?:boolean;requiresEntitlement:boolean};maturity?:string|null;monetizationReadiness?:number|null};
export type MarketplaceRegistry={registryVersion:string;name:string;generatedAt:string;generatedFrom?:string;sourceInventory:Record<string,unknown>;adapterTargets:Array<{id:AdapterPlatform;label:string;output:string}>;themes:string[];listings:MarketplaceListing[]};
type MarketplaceIndex=Omit<MarketplaceRegistry,"themes"|"listings">&{themes:Array<{name:string;file:string;count:number}>};
const marketplaceRoot=path.join(process.cwd(),"registries","marketplace"),packageRoot=path.join(process.cwd(),"packages","marketplace"),indexPath=path.join(marketplaceRoot,"marketplace.index.json");
function packageMeta(slug:string){const f=path.join(packageRoot,slug,"capability.json");if(!fs.existsSync(f))return null;try{return JSON.parse(fs.readFileSync(f,"utf8")) as Partial<MarketplaceListing>;}catch{return null;}}
export function marketplaceRegistry():MarketplaceRegistry{const index=JSON.parse(fs.readFileSync(indexPath,"utf8")) as MarketplaceIndex;const listings=index.themes.flatMap(t=>(JSON.parse(fs.readFileSync(path.join(marketplaceRoot,t.file),"utf8")) as MarketplaceListing[]).map(x=>({...x,...(packageMeta(x.slug)||{})})));return{registryVersion:index.registryVersion,name:index.name,generatedAt:index.generatedAt,generatedFrom:index.generatedFrom,sourceInventory:index.sourceInventory,adapterTargets:index.adapterTargets,themes:index.themes.map(t=>t.name),listings};}
export function marketplaceListings(){return marketplaceRegistry().listings;} export function getMarketplaceListing(slug:string){return marketplaceListings().find(x=>x.slug===slug)??null;}
export function getMarketplacePackageStatus(slug:string){const listing=getMarketplaceListing(slug);if(!listing)return null;const skillPath=path.join(packageRoot,slug,"SKILL.md");return{packagePath:listing.packagePath??`packages/marketplace/${slug}`,hasSkill:fs.existsSync(skillPath),instructionStatus:listing.instructionStatus??"source-unavailable"};}
export function searchMarketplace(params:{q?:string;theme?:string;kind?:string;platform?:string}={}){const q=(params.q??"").trim().toLowerCase(),theme=(params.theme??"").trim().toLowerCase(),kind=(params.kind??"").trim().toLowerCase(),platform=(params.platform??"").trim().toLowerCase();return marketplaceListings().filter(listing=>{const hay=[listing.name,listing.tagline,listing.description,listing.theme,listing.kind,...listing.capabilities].join(" ").toLowerCase();return(!q||hay.includes(q))&&(!theme||listing.theme.toLowerCase()===theme)&&(!kind||listing.kind.toLowerCase()===kind)&&(!platform||listing.platforms.some(x=>x.toLowerCase()===platform));});}
const stopWords=new Set(["the","a","an","and","or","to","of","for","with","my","i","want","need","help","me","on","in","from","that","this","is","are"]);function goalTokens(goal:string){return[...new Set(goal.toLowerCase().split(/[^a-z0-9]+/).filter(x=>x.length>2&&!stopWords.has(x)))];}
export function recommendMarketplace(goal:string,limit=6){const tokens=goalTokens(goal);return marketplaceListings().map(listing=>{const name=listing.name.toLowerCase(),theme=listing.theme.toLowerCase(),caps=listing.capabilities.join(" ").toLowerCase(),desc=(listing.tagline+" "+listing.description).toLowerCase();let score=0;const reasons:string[]=[];for(const token of tokens){let hit=0;if(name.includes(token))hit+=6;if(caps.includes(token))hit+=4;if(theme.includes(token))hit+=3;if(desc.includes(token))hit+=2;if(hit){score+=hit;reasons.push(token);}}if(listing.kind==="operator"&&reasons.length>=2)score+=3;return{listing,score,reasons:[...new Set(reasons)].slice(0,4)};}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||a.listing.name.localeCompare(b.listing.name)).slice(0,limit);}
function skillMarkdown(listing:MarketplaceListing){const f=path.join(packageRoot,listing.slug,"SKILL.md");if(fs.existsSync(f))return fs.readFileSync(f,"utf8");return`---\nname: ${listing.slug}\ndescription: ${JSON.stringify(listing.description)}\nmetadata:\n  version: ${listing.version}\n  instruction_status: source-unavailable\n---\n\n# ${listing.name}\n\n${listing.description}\n\n> Full canonical instructions are not yet present in this repository. Source provenance is preserved in capability.json.\n`;}
export function buildAdapter(platform:AdapterPlatform,listing:MarketplaceListing,baseUrl=""){const endpoint=`${baseUrl}/api/v1/plugins/${listing.slug}`,packageEndpoint=`${baseUrl}/api/v1/packages/${platform}/${listing.slug}`,mcpEndpoint=`${baseUrl}/api/mcp`,skill=skillMarkdown(listing),common={marketplace:"Operator Marketplace",registryVersion:marketplaceRegistry().registryVersion,packageEndpoint,plugin:{id:listing.id,slug:listing.slug,name:listing.name,version:listing.version,kind:listing.kind,theme:listing.theme,description:listing.description,components:listing.components??[],instructionStatus:listing.instructionStatus??"source-unavailable"}};switch(platform){case"openai":return{...common,adapter:"openai-skill",format:"skill-directory",files:[{path:"SKILL.md",content:skill},{path:"operator-marketplace.json",content:JSON.stringify({source:endpoint,mcp:mcpEndpoint},null,2)}]};case"claude":return{...common,adapter:"claude-agent-skill",format:"skill-directory",files:[{path:"SKILL.md",content:skill},{path:"marketplace.json",content:JSON.stringify({source:endpoint,mcp:mcpEndpoint},null,2)}],mcp:{url:mcpEndpoint}};case"codex":return{...common,adapter:"codex-plugin",format:"plugin-directory",files:[{path:".codex-plugin/plugin.json",content:JSON.stringify({name:listing.slug,version:listing.version,description:listing.tagline,skills:["skills/operator-marketplace/SKILL.md"]},null,2)},{path:"skills/operator-marketplace/SKILL.md",content:skill}],mcp:{url:mcpEndpoint}};case"mcp":return{...common,adapter:"mcp-remote",protocolVersion:"2026-07-28",transport:"streamable-http-jsonrpc",endpoint:mcpEndpoint,toolHints:["marketplace.search","marketplace.get","marketplace.adapter","marketplace.recommend","marketplace.package"]};case"api":return{...common,adapter:"rest-api",endpoints:{list:`${baseUrl}/api/v1/plugins`,get:endpoint,package:packageEndpoint,recommend:`${baseUrl}/api/v1/recommend`,openapi:`${baseUrl}/api/v1/openapi`}};case"vscode":return{...common,adapter:"vscode-workflow",recommendedTransport:"mcp",mcp:{url:mcpEndpoint},files:[{path:".vscode/operator-marketplace.json",content:JSON.stringify({plugin:listing.slug,registry:endpoint,package:packageEndpoint,mcp:mcpEndpoint},null,2)}]};case"saas":return{...common,adapter:"saas-capability",integration:{registry:endpoint,package:packageEndpoint,rest:`${baseUrl}/api/v1/plugins`,recommend:`${baseUrl}/api/v1/recommend`,mcp:mcpEndpoint,openapi:`${baseUrl}/api/v1/openapi`}};}}
